# Generated by Django 6.1 on 2026-08-15 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cabania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=254)),
                ('descripcion', models.TextField()),
                ('capacidad_personas', models.PositiveIntegerField(default=2)),
                ('precio_por_noche', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disponible', models.BooleanField(default=True)),
                ('caracteristicas', models.ManyToManyField(to='cabanias.caracteristica')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_clientes', models.CharField(max_length=50)),
                ('email_cliente', models.EmailField(max_length=254)),
                ('telefono_cliente', models.CharField(max_length=30)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_salida', models.DateField()),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('cabania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='cabanias.cabania')),
            ],
        ),
    ]
