# Generated by Django 6.1 on 2026-08-15 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabanias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cabania',
            options={'verbose_name': 'Cabaña', 'verbose_name_plural': 'Cabañas'},
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='nombre_clientes',
            new_name='nombre_cliente',
        ),
    ]
